# Generated by Django 2.2.7 on 2020-05-05 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_bet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата ставки'),
        ),
    ]
