# Generated by Django 2.2.7 on 2020-05-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_bet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='coefficient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.Coefficient', verbose_name='Коэффициент'),
        ),
    ]
