# Generated by Django 2.2.7 on 2020-05-01 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalanceFilRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, verbose_name='Сумма пополнения')),
                ('currency', models.CharField(max_length=255, verbose_name='Валюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент истории',
                'verbose_name_plural': 'История пополнения баланса',
            },
        ),
    ]
