# Generated by Django 2.2.7 on 2020-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userbalancefilrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancefilrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AddField(
            model_name='userbalancefilrecord',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Успешно пополнено!'),
        ),
    ]
