# Generated by Django 2.2.7 on 2020-05-02 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200502_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancefilrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
