# Generated by Django 2.2.7 on 2020-05-06 13:06

import bets.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200505_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promo_code',
            field=models.CharField(default=bets.utils.get_random_number, max_length=20, verbose_name='Промокод для регистрации'),
        ),
    ]
