# Generated by Django 2.2.7 on 2020-05-10 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_userbalancefilrecord_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbalancefilrecord',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Оплата проведена до конца?'),
        ),
        migrations.AlterField(
            model_name='userbalancefilrecord',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Успешно пополнено?'),
        ),
        migrations.AlterField(
            model_name='userbalancefilrecord',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Токен проверки'),
        ),
    ]
