# Generated by Django 2.2.7 on 2020-05-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200510_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='set_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ставки'),
        ),
    ]
