# Generated by Django 2.2.7 on 2020-05-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_transaction_set_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bonus_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transactions', to=settings.AUTH_USER_MODEL, verbose_name='От реферала'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BET_TRANSACTION', 'Ставка'), ('FILL_TRANSACTION', 'Пополнение баланса'), ('BONUS_TRANSACTION', 'Бонус от реферальной программы')], max_length=255, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
