# Generated by Django 2.2.7 on 2020-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200612_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertraffic',
            name='source',
            field=models.CharField(default='mkt', max_length=10, verbose_name='Source (src)'),
        ),
    ]
