# Generated by Django 2.2.7 on 2020-06-16 10:36

import bets.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_usertraffic_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalancefilrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='userbalancefilrecord',
            name='token',
            field=models.CharField(default=bets.utils.get_random_string, max_length=255, unique=True, verbose_name='Токен проверки'),
        ),
        migrations.AlterField(
            model_name='usertraffic',
            name='source',
            field=models.CharField(choices=[('mkt', 'Pixel'), ('cityads', 'CityAds')], default='mkt', max_length=10, verbose_name='Source (src)'),
        ),
    ]
