# Generated by Django 2.2.7 on 2020-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_trafficpercentpaymentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraffic',
            name='ip',
            field=models.CharField(max_length=16, verbose_name='User IP'),
        ),
    ]
