# Generated by Django 2.2.7 on 2020-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200616_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficpercentpaymentlog',
            name='traffic_info',
            field=models.TextField(blank=True, null=True, verbose_name='Инфо о траффике'),
        ),
    ]
