# Generated by Django 2.2.7 on 2020-07-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200617_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancefillconfiguration',
            name='page_footer',
            field=models.TextField(blank=True, help_text='Скрипты перед &lt;/body&gt;', null=True, verbose_name='FOOTER'),
        ),
        migrations.AlterField(
            model_name='balancefillconfiguration',
            name='page_header',
            field=models.TextField(blank=True, help_text='Скрипты &lt;head&gt;&lt;/head&gt;', null=True, verbose_name='HEADER'),
        ),
        migrations.CreateModel(
            name='UserClickTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16, verbose_name='IP')),
                ('area', models.CharField(choices=[('fill', 'Пополнение баланса'), ('sign-up', 'Регистрация')], max_length=255, verbose_name='Место клика')),
                ('traffic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserTraffic', verbose_name='Траффик')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Трекер кликов',
            },
        ),
    ]
