# Generated by Django 2.2.7 on 2020-07-02 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200702_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclicktracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
